jobs:
  build_deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
      - name: Installing AWS CLI
      - command:
          sudo apt-get update
          sudo apt install python3-pip
          sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
      - run: aws s3 sync ./app/build s3://mission04bucket-v2

workflows: 
  execute_bulk: 
    jobs: 
      - build_deploy
  version: 2
